name: test environment secret

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: Show message
        run: |
          echo "not setting stage secret now"
      - name: show secret value
        run: |
          echo "My secret is: ${{ secrets.API_KEY }}"
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ vars.API_KEY }}
