name: test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Show workflow version
        run: |
          echo "Workflow version: 2.0-test_b_checkout"

      - name: checkout
        uses: actions/checkout@v4
